export const EVENT_TYPES = [
  { key: 'marriage', label: '嫁娶', icon: '💒' },
  { key: 'business', label: '开业', icon: '🏪' },
  { key: 'move', label: '搬家', icon: '🏠' },
  { key: 'groundbreaking', label: '动土', icon: '⛏️' },
  { key: 'burial', label: '安葬', icon: '🪦' },
  { key: 'travel', label: '出行', icon: '✈️' },
  { key: 'contract', label: '签约', icon: '📝' },
  { key: 'sacrifice', label: '祭祀', icon: '🕯️' },
] as const

export const WEEKDAY_NAMES = ['日', '一', '二', '三', '四', '五', '六']

export const WEEKDAY_COLORS = [
  'text-fire',
  'text-text-primary',
  'text-text-primary',
  'text-text-primary',
  'text-text-primary',
  'text-text-primary',
  'text-water',
]

export const ZHI_CHONG: Record<string, string> = {
  '子': '马', '丑': '羊', '寅': '猴', '卯': '鸡', '辰': '狗', '巳': '猪',
  '午': '鼠', '未': '牛', '申': '虎', '酉': '兔', '戌': '龙', '亥': '蛇',
}

export const ZHI_SHA: Record<string, string> = {
  '子': '煞南', '丑': '煞东', '寅': '煞北', '卯': '煞西', '辰': '煞南', '巳': '煞东',
  '午': '煞北', '未': '煞西', '申': '煞南', '酉': '煞东', '戌': '煞北', '亥': '煞西',
}

export const JI_SHEN_NAMES: Record<string, string> = {
  'tianDe': '天德',
  'yueDe': '月德',
  'tianEn': '天恩',
  'muCang': '母仓',
  'shiYang': '时阳',
  'shengQi': '生气',
  'yiMa': '驿马',
  'tianMa': '天马',
  'deHe': '德合',
  'puHu': '普护',
  'tianGuan': '天官',
  'fuSheng': '福生',
  'tianXi': '天喜',
  'tianYi': '天医',
  'sanHe': '三合',
  'liuHe': '六合',
  'jinKui': '金匮',
  'tianCang': '天仓',
  'jinTang': '金堂',
  'mingTang': '明堂',
  'siXiang': '四相',
  'yinDe': '阴德',
  'minRi': '民日',
  'yuTang': '玉堂',
  'tianFu': '天福',
  'guanRi': '官日',
  'jiQing': '吉庆',
  'xuAn': '续世',
  'xiShen': '喜神',
  'caiXi': '财喜',
}

export const XIONG_SHEN_NAMES: Record<string, string> = {
  'tianGang': '天罡',
  'diSha': '地煞',
  'yueSha': '月煞',
  'yueJian': '月建',
  'yueXing': '月刑',
  'heKui': '河魁',
  'wangWang': '亡亡',
  'wuXu': '五虚',
  'tianZhu': '天柱',
  'liuBu': '六不',
  'guiKu': '鬼哭',
  'xueZhi': '血支',
  'youHuo': '游祸',
  'tianHuo': '天火',
  'diHuo': '地火',
  'siQi': '死气',
  'siFu': '四废',
  'wuLi': '五离',
  'baLong': '八龙',
  'baFeng': '八风',
  'baZuo': '八座',
  'jiKong': '天空',
  'xiaoHao': '小耗',
  'daHao': '大耗',
  'tianZei': '天贼',
  'diNang': '地囊',
  'huoShen': '火星',
  'heSha': '河煞',
  'bingSi': '兵吉',
  'wangRi': '往亡',
  'guiJi': '归忌',
  'chongRi': '冲日',
  'poRi': '破日',
  'biRi': '闭日',
  'jieRi': '劫日',
  'zaiRi': '灾日',
}
